name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-18.04

    steps:
      - name: Project checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: '3.8.6'

      - name: Install Poetry
        uses: snok/install-poetry@v1.2
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: make install

      - name: Check codestyle
        run: make checkstyle

      - name: Run tests
        run: make pytests

      - name: Upload test reports to Codecov
        uses: codecov/codecov-action@v1.5.2
